version: '3.8'

services:
  mariadb:
    image: mariadb:11
    restart: always
    container_name: mariadb-bost
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bost_db
      MARIADB_USER: pablo
      MARIADB_PASSWORD: pablo123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
